name: if condition
on: workflow_dispatch

jobs:
  condition:
    runs-on: ubuntu-latest
    steps:
      - name: deplyong changes only on main branch
        if: github.ref == 'refs/heads/main'
        run: echo "code is being deployed on main branch"
      - name: run this step
        run: echo "the pipeline is running"
      - name: run this steps
        run: |
          echo "${{ github.ref_name }}"
          echo "${{ github.sha }}" 
          echo "${{ github.run_number }}"
          echo "${{ github.run_id }}"
          echo "printenv"  
       
    
