name: input concepts
on:
  workflow_dispatch:
    inputs:
      environment:
        description: input environment to choose to deploy
        required: true
        default: dev
        type: choice
        options:
          - dev
          - prod
          - QA
      artifacts_tags:
        description: choose the git tag to deploy
        required: true
      
      
jobs:
  input:
    runs-on: ubuntu-latest
    steps:
      - name: deploy the app
        run: echo "Deploying the application ${{ inputs.environment }}
