name: context demo
on:
  push:
    branches:
      - main
      - qa

  pull_request:
    branches:
      - main

jobs:
  context-demo:
    runs-on: ubuntu-latest
    steps:
      - name: context demo setup
        run: |
          echo "this workflow is trigger by ${{ github.actor }}"
          echo "this repository name is ${{ github.repository }}"
          echo "The branch you picked ${{ github.ref_name }}"
          echo "the workflow type ${{ github.workflow}}"

      - name: showing all github variables
        run: echo "${{ toJson(github) }}"
          
